{{- if and .Values.loki.enabled .Values.loki.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-loki" (include "observability.fullname" .)) .Values.loki.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: loki
{{- end }}
