{{- if .Values.otelCollector.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "observability.fullname" . }}-otel
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel-collector
spec:
  selector:
    matchLabels:
      {{- include "observability.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: otel-collector
  template:
    metadata:
      labels:
        {{- include "observability.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: otel-collector
    spec:
      serviceAccountName: {{ default (printf "%s-otel" (include "observability.fullname" .)) .Values.otelCollector.serviceAccount.name }}
      {{- with .Values.otelCollector.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.otelCollector.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.otelCollector.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: otel-collector
          image: "{{ .Values.otelCollector.image.repository }}:{{ .Values.otelCollector.image.tag }}"
          imagePullPolicy: {{ .Values.otelCollector.image.pullPolicy }}
          args:
            - "--config=/etc/otel/collector-config.yaml"
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - name: otlp-grpc
              containerPort: {{ .Values.otelCollector.ports.otlpGrpc }}
            - name: otlp-http
              containerPort: {{ .Values.otelCollector.ports.otlpHttp }}
            - name: metrics
              containerPort: {{ .Values.otelCollector.ports.metrics }}
          resources:
            {{- toYaml .Values.otelCollector.resources | nindent 12 }}
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otel
              readOnly: true
      volumes:
        - name: otel-config
          configMap:
            name: {{ include "observability.fullname" . }}-otel-config
            items:
              - key: collector-config.yaml
                path: collector-config.yaml
{{- end }}
