{{- if and .Values.promtail.enabled .Values.promtail.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s-promtail" (include "observability.fullname" .)) .Values.promtail.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: promtail
{{- end }}
