{{- if .Values.promtail.enabled }}
{{- $fullName := include "observability.fullname" . -}}
{{- $saName := ternary (default (printf "%s-promtail" $fullName) .Values.promtail.serviceAccount.name) .Values.promtail.serviceAccount.name .Values.promtail.serviceAccount.create -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $fullName }}-promtail
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: promtail
spec:
  selector:
    matchLabels:
      {{- include "observability.promtail.selectorLabels" . | nindent 6 }}
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        {{- include "observability.promtail.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ $saName }}
      containers:
        - name: promtail
          image: {{ .Values.promtail.image.repository }}:{{ .Values.promtail.image.tag }}
          imagePullPolicy: {{ .Values.promtail.image.pullPolicy }}
          args:
            - -config.file=/etc/promtail/promtail.yaml
            - -config.expand-env=true
          env:
            {{- range .Values.promtail.extraEnv }}
            - name: {{ .name }}
              value: {{ .value | quote }}
            {{- end }}
          volumeMounts:
            - name: promtail-config
              mountPath: /etc/promtail
            - name: varlog
              mountPath: /var/log
            - name: varlibdocker
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: varlibpods
              mountPath: /var/log/pods
              readOnly: true
            - name: runjournal
              mountPath: /run/log/journal
              readOnly: true
          resources:
            {{- toYaml .Values.promtail.resources | nindent 12 }}
      {{- with .Values.promtail.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.promtail.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.promtail.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: promtail-config
          configMap:
            name: {{ $fullName }}-promtail-config
            items:
              - key: promtail.yaml
                path: promtail.yaml
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlibdocker
          hostPath:
            path: /var/lib/docker/containers
        - name: varlibpods
          hostPath:
            path: /var/log/pods
        - name: runjournal
          hostPath:
            path: /run/log/journal
{{- end }}
