{{- if .Values.promtail.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "observability.fullname" . }}-promtail
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: promtail
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
{{- end }}
