{{- if and .Values.kubePrometheusStack.enabled .Values.kubePrometheusStack.prometheus.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "observability.fullname" . }}-platform-rules
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability.monitoring.labels" . | nindent 4 }}
    prometheus: {{ .Release.Name }}
    role: alert-rules
spec:
  groups:
    - name: platform.incident-response
      interval: 30s
      rules:
        - alert: KeycloakDown
          expr: sum(rate(keycloak_authentication_requests_total{outcome="success"}[5m])) == 0
          for: 5m
          labels:
            severity: critical
            component: authentication
            service: keycloak
          annotations:
            summary: "Keycloak authentication service is down"
            description: "No successful authentication requests were recorded in the last 5 minutes. Verify Keycloak availability and ingress routing."
            playbook_url: "https://admin.intellifin.com/playbooks/keycloak-down"
        - alert: AuditChainBreak
          expr: audit_chain_integrity_status == 0
          for: 1m
          labels:
            severity: critical
            component: audit
            service: admin-service
          annotations:
            summary: "Audit chain integrity compromised"
            description: "Tamper-evident audit hash verification failed. Investigate recent audit ingestion events immediately."
            playbook_url: "https://admin.intellifin.com/playbooks/audit-chain-break"
        - alert: MutualTlsHandshakeFailures
          expr: sum(increase(linkerd_tls_acceptor_events_total{event="tls_error"}[1m])) > 10
          for: 2m
          labels:
            severity: critical
            component: service-mesh
            service: istio-gateway
          annotations:
            summary: "mTLS handshake failures detected"
            description: "Linkerd reported more than 10 TLS handshake errors per minute over the last 2 minutes. Certificates or trust bundles may be invalid."
            playbook_url: "https://admin.intellifin.com/playbooks/mtls-failures"
        - alert: PlatformHighErrorRate
          expr: (sum(rate(http_requests_total{status=~"5.."}[5m])) / sum(rate(http_requests_total[5m]))) > 0.05
          for: 5m
          labels:
            severity: critical
            component: application
            service: platform
          annotations:
            summary: "High platform error rate detected"
            description: "5xx responses exceed 5% of total traffic for 5 minutes. Review recent deployments and dependent services."
            playbook_url: "https://admin.intellifin.com/playbooks/high-error-rate"
        - alert: VaultUnavailable
          expr: sum(up{job="vault"}) == 0
          for: 2m
          labels:
            severity: critical
            component: secrets
            service: vault
          annotations:
            summary: "Vault cluster unavailable"
            description: "HashiCorp Vault probes failed for 2 minutes. Secrets retrieval and database rotations may be impacted."
            playbook_url: "https://admin.intellifin.com/playbooks/vault-down"
        - alert: DatabaseConnectionPoolExhausted
          expr: min(intellifin_db_pool_available_connections) == 0
          for: 3m
          labels:
            severity: warning
            component: database
            service: sql-cluster
          annotations:
            summary: "Database connection pool exhausted"
            description: "No spare database connections available for at least 3 minutes. Investigate slow queries and pool sizing."
            playbook_url: "https://admin.intellifin.com/playbooks/db-connection-pool"
    - name: platform.availability
      interval: 1m
      rules:
        - alert: ServiceInstanceDown
          expr: kube_endpoint_address_not_ready > 0
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Service endpoint has unavailable pods"
            description: "{{`{{`}} $labels.namespace {{`}}`}}/{{`{{`}} $labels.service {{`}}`}} has {{`{{`}} $value {{`}}`}} endpoints reporting not ready."
        - alert: ApiGatewayHighErrorRate
          expr: sum(rate(http_server_duration_seconds_count{service="intellifin-api-gateway", http_status_code=~"5.."}[5m]))
            /
            sum(rate(http_server_duration_seconds_count{service="intellifin-api-gateway"}[5m]))
            > 0.05
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "API Gateway 5xx error rate is above 5%"
            description: "The API Gateway has sustained high error rates over the last 5 minutes. Investigate upstream dependencies."
        - alert: KeycloakTokenFailures
          expr: sum(rate(keycloak_authentication_requests_total{outcome="failed"}[5m])) > 5
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Keycloak authentication failures detected"
            description: "Keycloak is returning failed authentications at a rate above 5 per second."
{{- end }}
