{{- if .Values.promtail.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "observability.fullname" . }}-promtail-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "observability.labels" . | nindent 4 }}
    app.kubernetes.io/component: promtail
data:
  promtail.yaml: |
    server:
      log_level: {{ .Values.promtail.logLevel }}
      http_listen_port: 3101
      grpc_listen_port: 0
    clients:
      - url: http://{{ include "observability.fullname" . }}-loki:{{ .Values.loki.service.httpPort }}/loki/api/v1/push
        tenant_id: {{ .Values.promtail.tenantID }}
    positions:
      filename: {{ .Values.promtail.positionsPath }}
    scrape_configs:
      - job_name: kubernetes-pods
        pipeline_stages:
          - cri: {}
          - regex:
              expression: "{{ .Values.promtail.pipeline.nrcExpression }}"
              replace: "******/**/**"
          - regex:
              expression: "{{ .Values.promtail.pipeline.phoneExpression }}"
              replace: "+260*********"
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
            target_label: __path__
            replacement: /var/log/pods/$1/*$2/*.log
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: pod
          - action: replace
            source_labels: [__meta_kubernetes_namespace]
            target_label: namespace
          - action: replace
            source_labels: [__meta_kubernetes_pod_container_name]
            target_label: container
          - action: replace
            source_labels: [__meta_kubernetes_node_name]
            target_label: node
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
{{- end }}
