apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "admin-service.fullname" . }}
  labels:
    {{- include "admin-service.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.environment | default "Production" | quote }}
