{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "admin-service.fullname" . }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace }}
  labels:
    {{- include "admin-service.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "admin-service.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      path: /metrics
{{- end }}
