apiVersion: v1
kind: ServiceAccount
metadata:
  name: credit-assessment-service
  namespace: intellifin
  labels:
    app: credit-assessment-service
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: credit-assessment-service
  namespace: intellifin
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: credit-assessment-service
  namespace: intellifin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: credit-assessment-service
subjects:
- kind: ServiceAccount
  name: credit-assessment-service
  namespace: intellifin
