apiVersion: v1
kind: Service
metadata:
  name: credit-assessment-service
  labels:
    app: credit-assessment-service
spec:
  type: ClusterIP
  selector:
    app: credit-assessment-service
  ports:
    - name: http
      port: 8080
      targetPort: http
