apiVersion: v1
kind: ConfigMap
metadata:
  name: identity-service-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"
  ConnectionStrings__IdentityDb: "Server=identity-db.database.windows.net;Database=IdentityDb;TrustServerCertificate=true"
  Vault__Address: "http://vault.vault.svc.cluster.local:8200"
