apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "credit-assessment-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "credit-assessment-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "credit-assessment-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "credit-assessment-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "credit-assessment-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: {{ .Values.config.aspnetcoreEnvironment | quote }}
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        - name: ConnectionStrings__LmsDatabase
          valueFrom:
            secretKeyRef:
              name: {{ include "credit-assessment-service.fullname" . }}-secrets
              key: database-connection-string
        - name: ConnectionStrings__Redis
          value: {{ .Values.config.redis.connectionString | quote }}
        - name: RabbitMQ__Host
          value: {{ .Values.config.rabbitmq.host | quote }}
        - name: Vault__Address
          value: {{ .Values.config.vault.address | quote }}
        - name: Vault__Token
          valueFrom:
            secretKeyRef:
              name: {{ include "credit-assessment-service.fullname" . }}-secrets
              key: vault-token
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
