apiVersion: v1
kind: Service
metadata:
  name: credit-assessment-service
  labels:
    app: credit-assessment-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: credit-assessment-service
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
