apiVersion: v1
kind: Secret
metadata:
  name: identity-service-secrets
  labels:
    app: identity-service
type: Opaque
stringData:
  connection-string: "Server=sql-server;Database=IntellifinIdentity;User Id=identity_svc;Password=CHANGE_ME;TrustServerCertificate=True;"
