apiVersion: v1
kind: Service
metadata:
  name: identity-service
  labels:
    app: identity-service
spec:
  type: ClusterIP
  selector:
    app: identity-service
  ports:
    - name: http
      port: 80
      targetPort: 8080
