apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keycloak-ha
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity-provider
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: keycloak
