apiVersion: v1
kind: Namespace
metadata:
  name: keycloak
  annotations:
    linkerd.io/inject: enabled
  labels:
    app.kubernetes.io/name: keycloak
    monitoring: "enabled"
    pod-security.kubernetes.io/enforce: baseline
